# Generated by Django 6.0 on 2026-01-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_article_article_image_alter_article_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="article_images/",
                verbose_name="Makaleye Fotoğraf Ekleyin",
            ),
        ),
    ]
