# Generated by Django 6.0 on 2026-01-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-created_date"]},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-comment_date"]},
        ),
    ]
